name: CI/CD feature

on:
  push:
    branches:
      - feature/*

jobs:
  lint:
    uses: fraunhofer-iem/dodo-github-visualization/.github/workflows/lint.yml@main

  compile:
    uses: fraunhofer-iem/dodo-github-visualization/.github/workflows/compile.yml@main
    needs: lint
